#ifndef __GD_PROTOS_H__
#define __GD_PROTOS_H__

typedef int (*_gdAlphaBlend) (int dest, int src);
typedef gdImagePtr (*_gdImageCreate) (int sx, int sy);
typedef gdImagePtr (*_gdImageCreateTrueColor) (int sx, int sy);
typedef gdImagePtr (*_gdImageCreateFromPng) (FILE * fd);
typedef gdImagePtr (*_gdImageCreateFromPngCtx) (gdIOCtxPtr in);
typedef gdImagePtr (*_gdImageCreateFromPngPtr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromGif) (FILE * fd);
typedef gdImagePtr (*_gdImageCreateFromGifCtx) (gdIOCtxPtr in);
typedef gdImagePtr (*_gdImageCreateFromGifPtr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromWBMP) (FILE * inFile);
typedef gdImagePtr (*_gdImageCreateFromWBMPCtx) (gdIOCtx * infile);
typedef gdImagePtr (*_gdImageCreateFromWBMPPtr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromJpeg) (FILE * infile);
typedef gdImagePtr (*_gdImageCreateFromJpegCtx) (gdIOCtx * infile);
typedef gdImagePtr (*_gdImageCreateFromJpegPtr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromPngSource) (gdSourcePtr in);
typedef gdImagePtr (*_gdImageCreateFromGd) (FILE * in);
typedef gdImagePtr (*_gdImageCreateFromGdCtx) (gdIOCtxPtr in);
typedef gdImagePtr (*_gdImageCreateFromGdPtr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromGd2) (FILE * in);
typedef gdImagePtr (*_gdImageCreateFromGd2Ctx) (gdIOCtxPtr in);
typedef gdImagePtr (*_gdImageCreateFromGd2Ptr) (int size, void *data);
typedef gdImagePtr (*_gdImageCreateFromGd2Part) (FILE * in, int srcx, int srcy, int w,int h);
typedef gdImagePtr (*_gdImageCreateFromGd2PartCtx) (gdIOCtxPtr in, int srcx, int srcy,int w, int h);
typedef gdImagePtr (*_gdImageCreateFromGd2PartPtr) (int size, void *data, int srcx, int srcy,int w, int h);
typedef gdImagePtr (*_gdImageCreateFromXbm) (FILE * in);
typedef gdImagePtr (*_gdImageCreateFromXpm) (char *filename);
typedef void (*_gdImageDestroy) (gdImagePtr im);
typedef void (*_gdImageSetPixel) (gdImagePtr im, int x, int y, int color);
typedef int (*_gdImageGetPixel) (gdImagePtr im, int x, int y);
typedef int (*_gdImageGetTrueColorPixel) (gdImagePtr im, int x, int y);
typedef void (*_gdImageAABlend) (gdImagePtr im);
typedef void (*_gdImageLine) (gdImagePtr im, int x1, int y1, int x2, int y2, int color);
typedef void (*_gdImageDashedLine) (gdImagePtr im, int x1, int y1, int x2, int y2,int color);
typedef void (*_gdImageRectangle) (gdImagePtr im, int x1, int y1, int x2, int y2,int color);
typedef void (*_gdImageFilledRectangle) (gdImagePtr im, int x1, int y1, int x2, int y2,int color);
typedef int (*_gdImageBoundsSafe) (gdImagePtr im, int x, int y);
typedef void (*_gdImageChar) (gdImagePtr im, gdFontPtr f, int x, int y, int c,int color);
typedef void (*_gdImageCharUp) (gdImagePtr im, gdFontPtr f, int x, int y, int c,int color);
typedef void (*_gdImageString) (gdImagePtr im, gdFontPtr f, int x, int y,unsigned char *s, int color);
typedef void (*_gdImageStringUp) (gdImagePtr im, gdFontPtr f, int x, int y,unsigned char *s, int color);
typedef void (*_gdImageString16) (gdImagePtr im, gdFontPtr f, int x, int y,unsigned short *s, int color);
typedef void (*_gdImageStringUp16) (gdImagePtr im, gdFontPtr f, int x, int y,unsigned short *s, int color);
typedef int (*_gdFontCacheSetup) (void);
typedef void (*_gdFontCacheShutdown) (void);
typedef void (*_gdFreeFontCache) (void);
typedef void (*_gdImagePolygon) (gdImagePtr im, gdPointPtr p, int n, int c);
typedef void (*_gdImageOpenPolygon) (gdImagePtr im, gdPointPtr p, int n, int c);
typedef void (*_gdImageFilledPolygon) (gdImagePtr im, gdPointPtr p, int n, int c);
typedef int (*_gdImageColorAllocate) (gdImagePtr im, int r, int g, int b);
typedef int (*_gdImageColorAllocateAlpha) (gdImagePtr im, int r, int g, int b, int a);
typedef int (*_gdImageColorClosest) (gdImagePtr im, int r, int g, int b);
typedef int (*_gdImageColorClosestAlpha) (gdImagePtr im, int r, int g, int b, int a);
typedef int (*_gdImageColorClosestHWB) (gdImagePtr im, int r, int g, int b);
typedef int (*_gdImageColorExact) (gdImagePtr im, int r, int g, int b);
typedef int (*_gdImageColorExactAlpha) (gdImagePtr im, int r, int g, int b, int a);
typedef int (*_gdImageColorResolve) (gdImagePtr im, int r, int g, int b);
typedef int (*_gdImageColorResolveAlpha) (gdImagePtr im, int r, int g, int b, int a);
typedef void (*_gdImageColorDeallocate) (gdImagePtr im, int color);
typedef gdImagePtr (*_gdImageCreatePaletteFromTrueColor) (gdImagePtr im, int ditherFlag,int colorsWanted);
typedef void (*_gdImageTrueColorToPalette) (gdImagePtr im, int ditherFlag,int colorsWanted);
typedef void (*_gdImageColorTransparent) (gdImagePtr im, int color);
typedef void (*_gdImagePaletteCopy) (gdImagePtr dst, gdImagePtr src);
typedef void (*_gdImageGif) (gdImagePtr im, FILE * out);
typedef void (*_gdImagePng) (gdImagePtr im, FILE * out);
typedef void (*_gdImagePngCtx) (gdImagePtr im, gdIOCtx * out);
typedef void (*_gdImageGifCtx) (gdImagePtr im, gdIOCtx * out);
typedef void (*_gdImagePngEx) (gdImagePtr im, FILE * out, int level);
typedef void (*_gdImagePngCtxEx) (gdImagePtr im, gdIOCtx * out, int level);
typedef void (*_gdImageWBMP) (gdImagePtr image, int fg, FILE * out);
typedef void (*_gdImageWBMPCtx) (gdImagePtr image, int fg, gdIOCtx * out);
typedef void (*_gdFree) (void *m);
typedef void (*_gdImageJpeg) (gdImagePtr im, FILE * out, int quality);
typedef void (*_gdImageJpegCtx) (gdImagePtr im, gdIOCtx * out, int quality);
typedef void (*_gdImagePngToSink) (gdImagePtr im, gdSinkPtr out);
typedef void (*_gdImageGd) (gdImagePtr im, FILE * out);
typedef void (*_gdImageGd2) (gdImagePtr im, FILE * out, int cs, int fmt);
typedef void (*_gdImageEllipse) (gdImagePtr im, int cx, int cy, int w, int h,int color);
typedef void (*_gdImageFilledArc) (gdImagePtr im, int cx, int cy, int w, int h, int s,int e, int color, int style);
typedef void (*_gdImageArc) (gdImagePtr im, int cx, int cy, int w, int h, int s, int e,int color);
typedef void (*_gdImageFilledEllipse) (gdImagePtr im, int cx, int cy, int w, int h,int color);
typedef void (*_gdImageFillToBorder) (gdImagePtr im, int x, int y, int border,int color);
typedef void (*_gdImageFill) (gdImagePtr im, int x, int y, int color);
typedef void (*_gdImageCopy) (gdImagePtr dst, gdImagePtr src, int dstX, int dstY,int srcX, int srcY, int w, int h);
typedef void (*_gdImageCopyMerge) (gdImagePtr dst, gdImagePtr src, int dstX, int dstY,int srcX, int srcY, int w, int h, int pct);
typedef void (*_gdImageCopyMergeGray) (gdImagePtr dst, gdImagePtr src, int dstX,int dstY, int srcX, int srcY, int w, int h,int pct);
typedef void (*_gdImageCopyResized) (gdImagePtr dst, gdImagePtr src, int dstX, int dstY,int srcX, int srcY, int dstW, int dstH, int srcW,int srcH);
typedef void (*_gdImageCopyResampled) (gdImagePtr dst, gdImagePtr src, int dstX,int dstY, int srcX, int srcY, int dstW, int dstH,int srcW, int srcH);
typedef void (*_gdImageCopyRotated) (gdImagePtr dst,gdImagePtr src,double dstX, double dstY,int srcX, int srcY,int srcWidth, int srcHeight, int angle);
typedef void (*_gdImageSetBrush) (gdImagePtr im, gdImagePtr brush);
typedef void (*_gdImageSetTile) (gdImagePtr im, gdImagePtr tile);
typedef void (*_gdImageSetAntiAliased) (gdImagePtr im, int c);
typedef void (*_gdImageSetAntiAliasedDontBlend) (gdImagePtr im, int c, int dont_blend);
typedef void (*_gdImageSetStyle) (gdImagePtr im, int *style, int noOfPixels);
typedef void (*_gdImageSetThickness) (gdImagePtr im, int thickness);
typedef void (*_gdImageInterlace) (gdImagePtr im, int interlaceArg);
typedef void (*_gdImageAlphaBlending) (gdImagePtr im, int alphaBlendingArg);
typedef void (*_gdImageSaveAlpha) (gdImagePtr im, int saveAlphaArg);
typedef int (*_gdImageCompare) (gdImagePtr im1, gdImagePtr im2);
typedef void (*_gdImageSharpen) (gdImagePtr im, int pct);

#endif
